TRUNCATE TABLE `product`;
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('1', '1', 'iPhone 3g', 'MP001', '3000', 'iPhone 3g 移动电话');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('2', '1', 'iPhone 3gs', 'MP002', '3500', 'iPhone 3gs 移动电话');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('3', '2', 'iPad 2', 'TC001', '3000', 'iPad 2 平板电脑');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('4', '1', 'iPhone 4', 'MP003', '4000', 'iPhone 4 移动电话');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('5', '1', 'iPhone 4s', 'MP004', '4500', 'iPhone 4s 移动电话');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('6', '2', 'iPad 3', 'TC002', '3000', 'iPad 3 平板电脑');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('7', '1', 'iPhone 5', 'MP005', '5000', 'iPhone 5 移动电话');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('8', '2', 'iPad mini', 'TC003', '3000', 'iPad mini 平板电脑');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('9', '1', '1', '1', '1', '');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('10', '1', '2', '2', '2', '');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('11', '1', '3', '3', '3', '');
INSERT INTO `product` (`id`, `product_type_id`, `product_name`, `product_code`, `price`, `description`) VALUES ('12', '1', '4', '4', '4', '');